
name: google_maps_place_picker
description: A Flutter plugin which provides 'Picking Place' using Google Maps widget.
version: 2.0.1
homepage: https://github.com/fysoul17/google_maps_place_picker

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.10.5"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.2.0
  geolocator: ^9.0.2
  permission_handler: ^10.4.5
  provider: ^6.1.1
  google_maps_webservice: ^0.0.20-nullsafety.2
  google_api_headers: ^1.6.0
  tuple: ^2.0.0-nullsafety.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  http: any

flutter:


