name: google_maps_place_picker_mb
description: A Flutter plugin which provides 'Picking Place' using Google Maps
  widget. (MB version)
version: 2.0.0-mb.22
homepage: https://github.com/martin-braun/google_maps_place_picker_mb

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=2.10.5'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  google_api_headers: ^1.5.0+1
  google_maps_flutter: ^2.2.5
  google_maps_webservice: ^0.0.20-nullsafety.5
  http: ^1.1.0
  location: ^4.4.0
  provider: ^6.0.5
  tuple: ^2.0.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  http: any

flutter: null

false_secrets:
  - /example/lib/keys.dart
  - /example/android/app/src/main/AndroidManifest.xml
  - /example/ios/Runner/AppDelegate.swift
